//! Structural fixture test (W29, dev-plan "Tests first: capability fixture denies read/
//! HTTP/shell") over the **files**, not just code that reads them at runtime: parses
//! `capabilities/default.json` and `tauri.conf.json` and asserts them field-for-field
//! against ui.md §3.1 (CSP) / §3.2 (grant/deny list) and api.md §8. An accidental
//! widening of either file — a stray `fs:allow-read`, a loosened CSP host, a missing
//! `dialog:allow-open` deny — fails this test instead of only failing review.
//!
//! `include_str!` pulls both files in at compile time so this test cannot pass against a
//! stale copy; it always sees exactly what `tauri-build` will also parse.

use serde_json::Value;

use crate::commands::COMMAND_NAMES;

const CAPABILITIES_JSON: &str = include_str!("../capabilities/default.json");
const TAURI_CONF_JSON: &str = include_str!("../tauri.conf.json");

/// ui.md §3.1's exact production CSP string.
const EXPECTED_CSP: &str = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' blob: data:; media-src 'none'; connect-src 'self' ipc: http://ipc.localhost; frame-src blob:; object-src 'none'; base-uri 'none'; form-action 'none';";

#[test]
fn csp_matches_ui_spec_byte_for_byte() {
    let conf: Value = serde_json::from_str(TAURI_CONF_JSON).expect("valid tauri.conf.json");
    let csp = conf["app"]["security"]["csp"]
        .as_str()
        .expect("app.security.csp is a string");
    assert_eq!(csp, EXPECTED_CSP, "tauri.conf.json CSP drifted from ui.md §3.1");
}

#[test]
fn csp_has_no_https_in_connect_src() {
    // ui.md §3.1: "No `https:` in `connect-src`. Cloud AI HTTP is Rust-only (C-ARCH-2)."
    let conf: Value = serde_json::from_str(TAURI_CONF_JSON).expect("valid tauri.conf.json");
    let csp = conf["app"]["security"]["csp"].as_str().unwrap();
    let connect_src_clause = csp
        .split(';')
        .find(|clause| clause.trim_start().starts_with("connect-src"))
        .expect("connect-src clause present");
    assert!(
        !connect_src_clause.contains("https:"),
        "connect-src must not contain https: (C-ARCH-2)"
    );
}

fn capability_json() -> Value {
    serde_json::from_str(CAPABILITIES_JSON).expect("valid capabilities/default.json")
}

fn str_array(v: &Value, key: &str) -> Vec<String> {
    v[key]
        .as_array()
        .unwrap_or_else(|| panic!("{key} is a JSON array"))
        .iter()
        .map(|e| e.as_str().expect("array entry is a string").to_string())
        .collect()
}

#[test]
fn grants_every_api_md_command_by_name() {
    // ui.md §3.2: "Grant: every command in api.md §5". Permission identifiers are
    // `allow-$command` with `_` slugified to `-` (tauri-build's autogenerated app-manifest
    // convention — see build.rs).
    let cap = capability_json();
    let permissions = str_array(&cap, "permissions");
    for command in COMMAND_NAMES {
        let slug = command.replace('_', "-");
        let identifier = format!("allow-{slug}");
        assert!(
            permissions.contains(&identifier),
            "capabilities/default.json is missing `{identifier}` for command `{command}`"
        );
    }
    assert_eq!(
        COMMAND_NAMES.len(),
        32,
        "api.md §5 lists 32 commands — update this fixture if that count changes"
    );
}

#[test]
fn grants_event_listen_for_both_events() {
    let cap = capability_json();
    let permissions = str_array(&cap, "permissions");
    assert!(permissions.contains(&"core:event:allow-listen".to_string()));
}

#[test]
fn grants_dialog_save_only_never_open() {
    let cap = capability_json();
    let permissions = str_array(&cap, "permissions");
    let deny = str_array(&cap, "deny");
    assert!(permissions.contains(&"dialog:allow-save".to_string()));
    assert!(
        !permissions.contains(&"dialog:allow-open".to_string()),
        "dialog open must never be granted (do-not fence)"
    );
    assert!(
        deny.contains(&"dialog:allow-open".to_string()),
        "dialog open must be explicitly denied"
    );
}

#[test]
fn grants_fs_write_only_never_read() {
    // ui.md §3.2: "Grant for persist only: @tauri-apps/plugin-fs write of in-memory bytes
    // to the path the save dialog just returned (writeFile / writeTextFile). Deny read,
    // readDir, remove, exists, and watch."
    let cap = capability_json();
    let permissions = str_array(&cap, "permissions");
    let deny = str_array(&cap, "deny");

    assert!(permissions.contains(&"fs:allow-write-file".to_string()));
    assert!(permissions.contains(&"fs:allow-write-text-file".to_string()));

    for forbidden in [
        "fs:allow-read",
        "fs:allow-read-dir",
        "fs:allow-read-file",
        "fs:allow-remove",
        "fs:allow-exists",
        "fs:allow-watch",
    ] {
        assert!(
            !permissions.contains(&forbidden.to_string()),
            "{forbidden} must never be granted (do-not fence)"
        );
        assert!(
            deny.contains(&forbidden.to_string()),
            "{forbidden} must be explicitly denied"
        );
    }
}

#[test]
fn denies_http_and_shell_entirely() {
    let cap = capability_json();
    let permissions = str_array(&cap, "permissions");
    let deny = str_array(&cap, "deny");

    for identifier in &permissions {
        assert!(
            !identifier.starts_with("http:") && !identifier.starts_with("shell:"),
            "http/shell must never be granted, found `{identifier}`"
        );
    }
    assert!(deny.contains(&"http:default".to_string()));
    assert!(deny.iter().any(|d| d.starts_with("shell:")));
}
